package tn.jihen.pfa.strategy.payement;

public enum PayementStrategyName {
    PAYEMENT_STRATEGY_ETUDIANT,
    PAYEMENT_STRATEGY_SALARIE,
    PAYEMENT_STRATEGY_SERVICE,
    PAYEMENT_STRATEGY_VACATAIR,
    PAYEMENT_STRATEGY_REMBOURSEMENT,
    PAYEMENT_STRATEGY_AVANCE,

}
